name: "ZeroTier"
description: "Connect your Github Action workflow to ZeroTier"
branding:
  icon: "globe"
  color: "gray-dark"

inputs:
  network_id:
    description: "The ZeroTier network ID to connect to"
    required: true
  auth_token:
    description: "Your ZeroTier Central API Access Token"
    required: true
  api_url:
    description: "ZeroTier Central API URL"
    required: false
    default: "https://api.zerotier.com/api/v1"
  ip_assignments:
    description: "Comma-separated list of IPs to assign to the runner (e.g. 10.0.0.5,10.0.0.6). Empty for auto-assign"
    required: false
    default: ""
  member_name:
    description: "Custom name for the member in ZeroTier Central. Defaults to 'Zerotier GitHub Member <short-sha>'"
    required: false
    default: ""
  member_description:
    description: "Custom description for the member in ZeroTier Central. Defaults to a link to the workflow run"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: zerotier
      uses: zalfafa/zt-action/util/post@main
      env:
        API_URL: ${{ inputs.api_url }}
        AUTH_TOKEN: ${{ inputs.auth_token }}
        NETWORK_ID: ${{ inputs.network_id }}
        IP_ASSIGNMENTS: ${{ inputs.ip_assignments }}
        MEMBER_NAME: ${{ inputs.member_name }}
        MEMBER_DESCRIPTION: ${{ inputs.member_description }}
      with:
        main: $GITHUB_ACTION_PATH/main.sh
        post: $GITHUB_ACTION_PATH/post.sh
